### PR TITLE
add and update fws

### PR DESCRIPTION
**Pull request by CvH**
see commit messages for details

### CODE REVIEW

**Comment by CvH** [comment]
because I can't test it better only pull if for >=OE7

**Comment by trsqr** [comment]
@CvH the Si2168-A20 firmware in this package is the really old 2.0.5 version that does not support PLP handling. As a result my TechnoTrend CT2-4650CI does not tune to any DVB-T2 channel.

You should have the 2.0.35 version instead:
-rw-r--r-- 1 root root 28656 Mar  3 10:26 /lib/firmware/dvb-demod-si2168-a20-01.fw
32e06713b33915f674bfb2c209beaea5  /lib/firmware/dvb-demod-si2168-a20-01.fw

This can be downloaded from:
http://palosaari.fi/linux/v4l-dvb/firmware/Si2168/Si2168-A20/32e06713b33915f674bfb2c209beaea5/dvb-demod-si2168-a20-01.fw

**Comment by CvH** [comment]
@trsqr 
done #25, got this fw from dvbsky with a much newer timestamp :(
Is there an way to check the versions of the fw's if you didn't have the hw?

**Comment by trsqr** [comment]
@CvH not sure really. With the HW you get a nice printout when the firmware is loaded. I tried to search for some strings in the firmware itself, but did not find any...

**Comment by CvH** [comment]
@trsqr okay so lets keep playing try and error ;-)

**Pull request merged**
