### PR TITLE
dvb-firmware: add firmware for Montage M88RS6000 DVB-S2 demod/tuner

### PR DESCRIPTION
**Pull request by trsqr**
Add firmware for Montage M88RS6000 satellite demod/tuner. Required to enable support for Hauppauge HVR-5255 (possibly others too).

### CODE REVIEW

**Comment by trsqr** [comment]
Actually we have dvb-fe-rs6000.fw there already, which I believe is not used by any driver anymore (was used by the non-mainline DVBSky before, I believe).

**Comment by stefansaraev** [comment]
> Actually we have dvb-fe-rs6000.fw

yup. what about just renaming the file (md5sums match)

btw, we still have a nonmainline dvbsky drivers for imx6. but it doesnt use dvb-fe-rs6000.fw. that's probably leftover from some even-older non mainline patch we had ;)

**Comment by trsqr** [comment]
Oh, already pushed a delete of the old one to this. If you prefer rename, can do that as well...

Actually M88RS6000 is rather new, but it's only used in some DVBSky "v3" PCIe devices, so I guess not applicable for iMX6 anyways.

**Comment by stefansaraev** [comment]
yup. smipcie. I remember it well. thanks.

**Pull request merged**
